change spell selector cards allign
evgenynefedov/MythPath pull request #26
Opened 2023-09-09 20:41 UTC by URBi1

2023-09-09 22:20 UTC, evgenynefedov requested changes
This implementation adds a scroll, see the screenshot:
![image](https://github.com/evgenynefedov/MythPath/assets/134942738/96ce8689-54b7-46fa-b5cd-536f862688ae)

2023-09-10 08:54 UTC, URBi1 commented
This task was closely related to the previous one, which is why there were display issues initially. Now that the previous branch has been merged into master and a rebase has been performed, the scrolling issue should no longer be present.

2023-09-10 09:10 UTC, evgenynefedov commented
On my screen now there is another issue. I will merge this branch in order to check it together.

2023-09-10 09:10 UTC, evgenynefedov approved these changes

2023-09-10 09:11 UTC, merged